[plugin]
name = "__dash-jar-hdfs"
description = "Replaces the Azure storage jars in the mapreduce.tar.gz package on HDFS to DASH storage jars."
version = "1.0"
maintainer_name = "Hortonworks"
maintainer_email = ""
website_url = "http://github.com/sequenceiq/__dash-jar-hdfs"

[plugin.config]

[plugin.compatibility]